stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script:
    - export RUSTAM="blabla"
    - echo RUSTAM
    - echo $APP_NAME
    - echo $APP_ENV
    - echo $APP_KEY
    - echo $APP_DEBUG
    - echo $APP_URL
    - echo $DB_CONNECTION
    - echo $DB_HOST
    - echo $DB_PORT
    - echo $DB_DATABASE
    - echo $DB_USERNAME
    - echo $DB_PASSWORD

