stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script:
    - echo "another:$CI_COMMIT_SHA/$CI_COMMIT_TITLE/$CI_COMMIT_TAGS"

print_second:
  stage: second
  tags:
    - build
  only:
    - develop
  script:
    - echo $SOME
