stages:
  - first
  - second
  - third

print_first:
  stage: first
  tags:
    - build
  only:
    - develop
  script:
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_TITLE
    - echo $CI_COMMIT_TAG

print_second:
  stage: second
  tags:
    - build
  only:
    - develop
  script:
    - echo $CI_REGISTRY_USER
    - echo $CI_REGISTRY

print_third:
  stage: third
  tags:
    - build
  only:
    - develop
  script:
    - echo "hello world third"
