version: '3'
services:
    finsoft_server:
        image: "nginx:stable-alpine"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8100:80"
        depends_on:
            - finsoft_app
        container_name: ${CONTAINER_PREFIX}_server
    finsoft_app:
        image: $REGISTRY/dev/app:$CI_COMMIT_SHA
        environment:
          - APP_KEY=$APP_KEY
          - APP_NAME=$APP_NAME
          - APP_ENV=$APP_ENV
          - APP_URL=$APP_URL
          - DB_CONNECTION=$DB_CONNECTION
          - DB_HOST=$DB_HOST
          - DB_PORT=$DB_PORT
          - DB_DATABASE=$DB_DATABASE
          - DB_USERNAME=$DB_USERNAME
          - DB_PASSWORD=$DB_PASSWORD
          - APP_DEBUG=$APP_DEBUG
        volumes:
            - ./:/var/www
        depends_on:
            -   finsoft_database
        container_name: ${CONTAINER_PREFIX}_app
    finsoft_database:
        image: mysql:8.0
        restart: always
        volumes:
            -   ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: $DB_DATABASE
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
        ports:
            -   8103:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: ${CONTAINER_PREFIX}_database

