version: '3'
services:

    server:
        image: "nginx:stable-alpine"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8410:80"
        depends_on:
            - app
        container_name: server
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   database
        container_name: app
    database:
        image: mysql:8.0
        restart: always
        volumes:
            -   ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: finsoft
            MYSQL_ROOT_PASSWORD: root
        ports:
            -   8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: database
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
        container_name: elastic
        volumes:
            - laravelelastic:/usr/share/elasticsearch/data
        environment:
            - node.name=elastic
            - cluster.name=elastic-docker-cluster
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        networks:
            - laravel
        restart: unless-stopped
    kibana:
        image: docker.elastic.co/kibana/kibana:8.7.1
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_URL: "http://elastic:9200"
            ELASTICSEARCH_HOSTS: "http://elastic:9200"
        networks:
            - laravel
        depends_on:
            -   elastic
        restart: unless-stopped

volumes:
    laravelelastic:
        driver: local
networks:
    laravel:
        driver: bridge


