version: '3'
services:
    server_develop:
        image: "nginx:stable-alpine"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - "8410:80"
        depends_on:
            - app_develop
        container_name: server_develop
    app_develop:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   database_develop
        container_name: app_develop
    database_develop:
        image: mysql:8.0
        restart: always
        volumes:
            -   ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: finsoft
            MYSQL_ROOT_PASSWORD: root
        ports:
            -   8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: database_develop

